/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package MessagesSchemas;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class NewMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NewMessage\",\"namespace\":\"MessagesSchemas\",\"fields\":[{\"name\":\"messageId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"handlerName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"messageDetails\",\"type\":{\"type\":\"record\",\"name\":\"MessageDetails\",\"fields\":[{\"name\":\"sendingTime\",\"type\":[\"long\"],\"logicalType\":\"time-millis\"},{\"name\":\"messageContent\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"parsed\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"serviceId\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public String messageId;
  @Deprecated public String handlerName;
  @Deprecated public MessageDetails messageDetails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public NewMessage() {}

  /**
   * All-args constructor.
   */
  public NewMessage(String messageId, String handlerName, MessageDetails messageDetails) {
    this.messageId = messageId;
    this.handlerName = handlerName;
    this.messageDetails = messageDetails;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return messageId;
    case 1: return handlerName;
    case 2: return messageDetails;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: messageId = (String)value$; break;
    case 1: handlerName = (String)value$; break;
    case 2: messageDetails = (MessageDetails)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'messageId' field.
   */
  public String getMessageId() {
    return messageId;
  }

  /**
   * Sets the value of the 'messageId' field.
   * @param value the value to set.
   */
  public void setMessageId(String value) {
    this.messageId = value;
  }

  /**
   * Gets the value of the 'handlerName' field.
   */
  public String getHandlerName() {
    return handlerName;
  }

  /**
   * Sets the value of the 'handlerName' field.
   * @param value the value to set.
   */
  public void setHandlerName(String value) {
    this.handlerName = value;
  }

  /**
   * Gets the value of the 'messageDetails' field.
   */
  public MessageDetails getMessageDetails() {
    return messageDetails;
  }

  /**
   * Sets the value of the 'messageDetails' field.
   * @param value the value to set.
   */
  public void setMessageDetails(MessageDetails value) {
    this.messageDetails = value;
  }

  /** Creates a new NewMessage RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new NewMessage RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new NewMessage RecordBuilder by copying an existing NewMessage instance */
  public static Builder newBuilder(NewMessage other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for NewMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NewMessage>
    implements org.apache.avro.data.RecordBuilder<NewMessage> {

    private String messageId;
    private String handlerName;
    private MessageDetails messageDetails;

    /** Creates a new Builder */
    private Builder() {
      super(NewMessage.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.messageId)) {
        this.messageId = data().deepCopy(fields()[0].schema(), other.messageId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.handlerName)) {
        this.handlerName = data().deepCopy(fields()[1].schema(), other.handlerName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.messageDetails)) {
        this.messageDetails = data().deepCopy(fields()[2].schema(), other.messageDetails);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing NewMessage instance */
    private Builder(NewMessage other) {
            super(NewMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.messageId)) {
        this.messageId = data().deepCopy(fields()[0].schema(), other.messageId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.handlerName)) {
        this.handlerName = data().deepCopy(fields()[1].schema(), other.handlerName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.messageDetails)) {
        this.messageDetails = data().deepCopy(fields()[2].schema(), other.messageDetails);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'messageId' field */
    public String getMessageId() {
      return messageId;
    }
    
    /** Sets the value of the 'messageId' field */
    public Builder setMessageId(String value) {
      validate(fields()[0], value);
      this.messageId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'messageId' field has been set */
    public boolean hasMessageId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'messageId' field */
    public Builder clearMessageId() {
      messageId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'handlerName' field */
    public String getHandlerName() {
      return handlerName;
    }
    
    /** Sets the value of the 'handlerName' field */
    public Builder setHandlerName(String value) {
      validate(fields()[1], value);
      this.handlerName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'handlerName' field has been set */
    public boolean hasHandlerName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'handlerName' field */
    public Builder clearHandlerName() {
      handlerName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'messageDetails' field */
    public MessageDetails getMessageDetails() {
      return messageDetails;
    }
    
    /** Sets the value of the 'messageDetails' field */
    public Builder setMessageDetails(MessageDetails value) {
      validate(fields()[2], value);
      this.messageDetails = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'messageDetails' field has been set */
    public boolean hasMessageDetails() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'messageDetails' field */
    public Builder clearMessageDetails() {
      messageDetails = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public NewMessage build() {
      try {
        NewMessage record = new NewMessage();
        record.messageId = fieldSetFlags()[0] ? this.messageId : (String) defaultValue(fields()[0]);
        record.handlerName = fieldSetFlags()[1] ? this.handlerName : (String) defaultValue(fields()[1]);
        record.messageDetails = fieldSetFlags()[2] ? this.messageDetails : (MessageDetails) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
