/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package MessagesSchemas;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MessageDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageDetails\",\"namespace\":\"MessagesSchemas\",\"fields\":[{\"name\":\"sendingTime\",\"type\":[\"long\"],\"logicalType\":\"time-millis\"},{\"name\":\"messageContent\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"parsed\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"},{\"name\":\"serviceId\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"default\":\"null\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Object sendingTime;
  @Deprecated public java.lang.String messageContent;
  @Deprecated public java.lang.String parsed;
  @Deprecated public java.lang.String serviceId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public MessageDetails() {}

  /**
   * All-args constructor.
   */
  public MessageDetails(java.lang.Object sendingTime, java.lang.String messageContent, java.lang.String parsed, java.lang.String serviceId) {
    this.sendingTime = sendingTime;
    this.messageContent = messageContent;
    this.parsed = parsed;
    this.serviceId = serviceId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sendingTime;
    case 1: return messageContent;
    case 2: return parsed;
    case 3: return serviceId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sendingTime = (java.lang.Object)value$; break;
    case 1: messageContent = (java.lang.String)value$; break;
    case 2: parsed = (java.lang.String)value$; break;
    case 3: serviceId = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sendingTime' field.
   */
  public java.lang.Object getSendingTime() {
    return sendingTime;
  }

  /**
   * Sets the value of the 'sendingTime' field.
   * @param value the value to set.
   */
  public void setSendingTime(java.lang.Object value) {
    this.sendingTime = value;
  }

  /**
   * Gets the value of the 'messageContent' field.
   */
  public java.lang.String getMessageContent() {
    return messageContent;
  }

  /**
   * Sets the value of the 'messageContent' field.
   * @param value the value to set.
   */
  public void setMessageContent(java.lang.String value) {
    this.messageContent = value;
  }

  /**
   * Gets the value of the 'parsed' field.
   */
  public java.lang.String getParsed() {
    return parsed;
  }

  /**
   * Sets the value of the 'parsed' field.
   * @param value the value to set.
   */
  public void setParsed(java.lang.String value) {
    this.parsed = value;
  }

  /**
   * Gets the value of the 'serviceId' field.
   */
  public java.lang.String getServiceId() {
    return serviceId;
  }

  /**
   * Sets the value of the 'serviceId' field.
   * @param value the value to set.
   */
  public void setServiceId(java.lang.String value) {
    this.serviceId = value;
  }

  /** Creates a new MessageDetails RecordBuilder */
  public static MessagesSchemas.MessageDetails.Builder newBuilder() {
    return new MessagesSchemas.MessageDetails.Builder();
  }
  
  /** Creates a new MessageDetails RecordBuilder by copying an existing Builder */
  public static MessagesSchemas.MessageDetails.Builder newBuilder(MessagesSchemas.MessageDetails.Builder other) {
    return new MessagesSchemas.MessageDetails.Builder(other);
  }
  
  /** Creates a new MessageDetails RecordBuilder by copying an existing MessageDetails instance */
  public static MessagesSchemas.MessageDetails.Builder newBuilder(MessagesSchemas.MessageDetails other) {
    return new MessagesSchemas.MessageDetails.Builder(other);
  }
  
  /**
   * RecordBuilder for MessageDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageDetails>
    implements org.apache.avro.data.RecordBuilder<MessageDetails> {

    private java.lang.Object sendingTime;
    private java.lang.String messageContent;
    private java.lang.String parsed;
    private java.lang.String serviceId;

    /** Creates a new Builder */
    private Builder() {
      super(MessagesSchemas.MessageDetails.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(MessagesSchemas.MessageDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sendingTime)) {
        this.sendingTime = data().deepCopy(fields()[0].schema(), other.sendingTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.messageContent)) {
        this.messageContent = data().deepCopy(fields()[1].schema(), other.messageContent);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.parsed)) {
        this.parsed = data().deepCopy(fields()[2].schema(), other.parsed);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.serviceId)) {
        this.serviceId = data().deepCopy(fields()[3].schema(), other.serviceId);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing MessageDetails instance */
    private Builder(MessagesSchemas.MessageDetails other) {
            super(MessagesSchemas.MessageDetails.SCHEMA$);
      if (isValidValue(fields()[0], other.sendingTime)) {
        this.sendingTime = data().deepCopy(fields()[0].schema(), other.sendingTime);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.messageContent)) {
        this.messageContent = data().deepCopy(fields()[1].schema(), other.messageContent);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.parsed)) {
        this.parsed = data().deepCopy(fields()[2].schema(), other.parsed);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.serviceId)) {
        this.serviceId = data().deepCopy(fields()[3].schema(), other.serviceId);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'sendingTime' field */
    public java.lang.Object getSendingTime() {
      return sendingTime;
    }
    
    /** Sets the value of the 'sendingTime' field */
    public MessagesSchemas.MessageDetails.Builder setSendingTime(java.lang.Object value) {
      validate(fields()[0], value);
      this.sendingTime = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'sendingTime' field has been set */
    public boolean hasSendingTime() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'sendingTime' field */
    public MessagesSchemas.MessageDetails.Builder clearSendingTime() {
      sendingTime = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'messageContent' field */
    public java.lang.String getMessageContent() {
      return messageContent;
    }
    
    /** Sets the value of the 'messageContent' field */
    public MessagesSchemas.MessageDetails.Builder setMessageContent(java.lang.String value) {
      validate(fields()[1], value);
      this.messageContent = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'messageContent' field has been set */
    public boolean hasMessageContent() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'messageContent' field */
    public MessagesSchemas.MessageDetails.Builder clearMessageContent() {
      messageContent = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'parsed' field */
    public java.lang.String getParsed() {
      return parsed;
    }
    
    /** Sets the value of the 'parsed' field */
    public MessagesSchemas.MessageDetails.Builder setParsed(java.lang.String value) {
      validate(fields()[2], value);
      this.parsed = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'parsed' field has been set */
    public boolean hasParsed() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'parsed' field */
    public MessagesSchemas.MessageDetails.Builder clearParsed() {
      parsed = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'serviceId' field */
    public java.lang.String getServiceId() {
      return serviceId;
    }
    
    /** Sets the value of the 'serviceId' field */
    public MessagesSchemas.MessageDetails.Builder setServiceId(java.lang.String value) {
      validate(fields()[3], value);
      this.serviceId = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'serviceId' field has been set */
    public boolean hasServiceId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'serviceId' field */
    public MessagesSchemas.MessageDetails.Builder clearServiceId() {
      serviceId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public MessageDetails build() {
      try {
        MessageDetails record = new MessageDetails();
        record.sendingTime = fieldSetFlags()[0] ? this.sendingTime : (java.lang.Object) defaultValue(fields()[0]);
        record.messageContent = fieldSetFlags()[1] ? this.messageContent : (java.lang.String) defaultValue(fields()[1]);
        record.parsed = fieldSetFlags()[2] ? this.parsed : (java.lang.String) defaultValue(fields()[2]);
        record.serviceId = fieldSetFlags()[3] ? this.serviceId : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
